-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXjwrTjupJIHYLeJu
9wVEmKOA9+RUud28qZzLzex8wXqgCgYIKoZIzj0DAQehRANCAATNkYcEkUbsTc3E
L5segszMmkcD88aoJOH2M0zZWoOQxvhWxPa4rSIiyLSZbjRj5stu0COLX6jk7Nbk
tAQIrtVc
-----END PRIVATE KEY-----